# Generated by Django 2.0.5 on 2018-05-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tblBasket',
        ),
    ]
