# Generated by Django 2.0.5 on 2018-05-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_delete_tblbasket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcustumers',
            name='index',
        ),
        migrations.DeleteModel(
            name='tblCustumers',
        ),
        migrations.DeleteModel(
            name='tblIndex',
        ),
    ]
